import { Eye, Search } from "lucide-react";
import { SectionHead } from "./AllFunc";
import { Reveal } from "./Reveal";

export default function Capabilities() {
    return (
        <section id="features" className="px-0 py-20 bg-[var(--bg)]"><div className="mx-auto max-w-[1200px] px-6"><Reveal><SectionHead eyebrow="Capabilities" title="One agent. The whole founding team.">Seven deeply-integrated modules that share a single, evolving understanding of your startup.</SectionHead></Reveal><div className="grid grid-cols-3 gap-5 max-[960px]:grid-cols-2 max-[640px]:grid-cols-1">
            {["Deep Market Research", "Document Generation Suite", "Idea Validation Engine", "Persistent Startup Memory", "Pitch Deck Builder", "Outreach Automation"].map((title, i) => <Reveal key={title}><div className="group relative h-full overflow-hidden rounded-[var(--radius)] border border-[var(--line)] bg-[linear-gradient(180deg,var(--panel),var(--bg-2))] p-[26px] transition duration-200 hover:-translate-y-[5px] hover:border-[var(--line-2)] hover:shadow-[var(--shadow)]">{i === 3 || i === 4 ? <span className="absolute right-[18px] top-[18px] rounded-full border border-[var(--cyan-border)] bg-[var(--cyan-soft)] px-[9px] py-[3px] text-[10.5px] font-bold text-[var(--brand-2)]">Core</span> : null}<div className="mb-[18px] grid h-12 w-12 place-items-center rounded-[13px] border border-[var(--line-2)] bg-[var(--grad-soft)]"><Search name={["search", "doc", "shield", "brain", "screen", "mail"][i]} size={22} stroke={["var(--brand)", "var(--brand-2)", "var(--brand-3)", "var(--brand)", "var(--brand-2)", "var(--brand-3)"][i]} /></div><h3 className="mb-[9px] text-[18.5px] font-semibold tracking-[-.01em]">{title}</h3><p className="text-[14.5px] text-[var(--muted)]">{["Autonomous agent maps competitive landscapes, sizes markets (TAM/SAM/SOM), and synthesizes trend reports across any industry.", "One prompt produces full PRDs, business plans, financial models, and investor-grade pitch decks with design-ready layouts.", "Applies SWOT, Jobs-to-be-Done, and Blue Ocean frameworks automatically to validate and stress-test new concepts.", "Long-term retention via vector embeddings — Solirna remembers your pivots, decisions, and constraints as your company evolves.", "Interactive builder with AI-generated content, slide-by-slide suggestions, and design recommendations aligned to investor expectations.", "AI-drafted cold emails, LinkedIn messages, and investor sequences — personalized from each recipient's background."][i]}</p></div></Reveal>)}
            <Reveal className="col-span-3 max-[960px]:col-span-2 max-[640px]:col-span-1"><div className="grid grid-cols-[auto_1fr] items-center gap-5 rounded-[var(--radius)] border border-[var(--line)] bg-[linear-gradient(180deg,var(--panel),var(--bg-2))] p-[26px] max-[640px]:grid-cols-1"><div className="grid h-14 w-14 place-items-center rounded-[13px] border border-[var(--line-2)] bg-[var(--grad-soft)]"><Eye size={26} stroke="var(--accent)" /></div><div><h3 className="mb-[9px] text-[18.5px] font-semibold">Strategic Brainstorm Partner</h3><p className="text-[14.5px] text-[var(--muted)]">Iterative ideation sessions where Solirna challenges your assumptions, proposes alternatives, and helps you pressure-test the decisions that matter most — like a co-founder who never sleeps.</p></div></div></Reveal>
        </div></div></section>
    )

}