import { navItems } from "@/lib/data"
import { Reveal } from "./Reveal"

export default function Demo() {
    return (
        <section id="demo" className="px-0 pb-20 pt-10"><div className="mx-auto max-w-[1200px] px-6"><Reveal><SectionHead eyebrow="Live, interactive demo" title="Take Solirna for a spin">This is a fully functional front-end prototype. Chat, generate a PRD, validate an idea, build a deck, and run research — all running right here in your browser.</SectionHead></Reveal>
            <Reveal><div className="grid min-h-[600px] grid-cols-[230px_1fr] overflow-hidden rounded-[24px] border border-[var(--line-2)] bg-[linear-gradient(180deg,var(--panel),var(--deep-panel))] shadow-[var(--shadow)] max-[960px]:grid-cols-1">
                <aside className="flex flex-col gap-1.5 border-r border-[var(--line)] bg-[var(--glass-015)] p-[18px_14px] max-[960px]:flex-row max-[960px]:flex-wrap max-[960px]:border-b max-[960px]:border-r-0">
                    <div className="mb-1.5 flex items-center gap-2.5 border-b border-[var(--line)] px-2 pb-4 max-[960px]:hidden"><div className="grid h-[34px] w-[34px] place-items-center rounded-[10px] bg-[var(--grad)] text-sm font-extrabold text-[var(--ink)]">A</div><div><b className="text-[13.5px]">Alex Rivera</b><small className="block text-[11.5px] text-[var(--muted)]">Founder · NovaForge</small></div></div>
                    {navItems.map(([id, label, icon]) => <button key={id} onClick={() => setView(id)} className={`flex cursor-pointer items-center gap-[11px] rounded-[11px] border px-3 py-2.5 text-left text-sm font-medium transition max-[960px]:flex-1 max-[960px]:justify-center max-[640px]:px-2 ${view === id ? "border-[var(--line-2)] bg-[var(--grad-soft)] text-[var(--white)]" : "border-transparent text-[var(--muted)] hover:bg-[var(--glass-04)] hover:text-[var(--text)]"}`}><Icon name={icon} size={18} /><span className="max-[640px]:hidden">{label}</span></button>)}
                    <div className="mt-auto rounded-xl border border-[var(--line-2)] bg-[var(--grad-soft)] p-3 text-xs text-[var(--muted)] max-[960px]:hidden"><b className="mb-0.5 block text-[var(--white)]">🧠 Startup Memory</b>Solirna remembers 38 facts about NovaForge.<div className="mt-2 h-1.5 overflow-hidden rounded-md bg-[var(--glass-08)]"><i className="block h-full w-[64%] bg-[var(--grad)]" /></div></div>
                </aside>
                <div className="flex min-h-[600px] flex-col"><div className="flex items-center justify-between border-b border-[var(--line)] px-[22px] py-4"><h3 className="text-base font-semibold tracking-[-.01em]">{titles[view]}</h3><span className="text-[12.5px] text-[var(--muted)] max-[640px]:hidden">Persistent memory: ON · Context: NovaForge</span></div>
                    <div className="relative flex-1 overflow-hidden">
                        {view === "chat" && <div className="flex h-full min-h-[500px] flex-col"><div className="flex max-h-[430px] flex-1 flex-col gap-4 overflow-y-auto p-[22px]">{messages.map((m, i) => <div key={i} className={`flex max-w-[90%] items-start gap-3 ${m.who === "me" ? "ml-auto flex-row-reverse" : ""}`}><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-[10px] text-[13px] font-extrabold ${m.who === "me" ? "border border-[var(--line-2)] bg-[var(--glass-08)] text-[var(--text)]" : "bg-[var(--grad)] text-[var(--ink)]"}`}>{m.who === "me" ? "A" : "S"}</div><div className={`rounded-[15px] px-4 py-[13px] text-[14.5px] leading-[1.6] ${m.who === "me" ? "bg-[var(--grad)] font-medium text-[var(--ink)]" : "border border-[var(--line)] bg-[var(--glass-04)] text-[var(--bubble-2)]"}`}>{m.html}{m.mem && <div className="mt-2 flex items-center gap-1.5 text-[11.5px] text-[var(--brand-2)]">🧠 {m.mem}</div>}</div></div>)}{typing && <div className="flex max-w-[90%] items-start gap-3"><div className="grid h-8 w-8 place-items-center rounded-[10px] bg-[var(--grad)] text-[13px] font-extrabold text-[var(--ink)]">S</div><div className="rounded-[15px] border border-[var(--line)] bg-[var(--glass-04)] px-4 py-[13px]"><div className="flex items-center gap-1"><i className="h-[7px] w-[7px] animate-bounce rounded-full bg-[var(--brand-2)]" /><i className="h-[7px] w-[7px] animate-bounce rounded-full bg-[var(--brand-2)] [animation-delay:150ms]" /><i className="h-[7px] w-[7px] animate-bounce rounded-full bg-[var(--brand-2)] [animation-delay:300ms]" /></div></div></div>}</div><div className="flex flex-wrap gap-2 px-[18px] pb-3.5">{["Validate my latest idea", "Draft an investor email", "What do you remember about us?", "Size my market"].map(x => <button key={x} onClick={() => sendChat(x)} className="cursor-pointer rounded-full border border-[var(--line)] bg-[var(--glass-04)] px-3 py-[7px] text-[12.5px] text-[var(--muted)] transition hover:border-[var(--brand)] hover:bg-[var(--grad-soft)] hover:text-[var(--white)]">{x}</button>)}</div><div className="flex items-center gap-2.5 border-t border-[var(--line)] p-4 px-[18px]"><input value={chatInput} onChange={e => setChatInput(e.target.value)} onKeyDown={e => { if (e.key === "Enter") sendChat() }} placeholder="Message your co-founder…" className="min-w-0 flex-1 rounded-xl border border-[var(--line-2)] bg-[var(--glass-04)] px-4 py-[13px] text-[14.5px] text-[var(--text)] outline-none placeholder:text-[var(--muted)] focus:border-[var(--brand)]" /><button onClick={() => sendChat()} className="grid h-[46px] w-[46px] shrink-0 cursor-pointer place-items-center rounded-xl bg-[var(--grad)]"><Icon name="send" size={20} stroke="var(--ink)" /></button></div></div>}

                        {view !== "chat" && <div className="max-h-[530px] overflow-y-auto p-6">
                            {view === "prd" && <><div className="mb-4"><label className="mb-1.5 block text-[13px] font-medium text-[var(--muted)]">Document type</label><select value={docType} onChange={e => setDocType(e.target.value)} className="w-full rounded-[11px] border border-[var(--line-2)] bg-[var(--glass-04)] px-3.5 py-3 text-sm text-[var(--text)] outline-none focus:border-[var(--brand)]"><option>Product Requirements Document (PRD)</option><option>Business Plan</option><option>Financial Projection Model</option><option>Lean Canvas</option></select></div><Field label="Product / idea" value={docIdea} onChange={setDocIdea} /><Field label="Target customer" value={docAud} onChange={setDocAud} /><Button primary onClick={generateDoc}>✨ Generate document</Button><OutputBox>{output.prd || <Placeholder>Your generated document will appear here — structured, editable, and saved to memory.</Placeholder>}</OutputBox></>}
                            {view === "validate" && <><TextAreaField label="Idea to validate" value={valIdea} onChange={setValIdea} /><Button primary onClick={generateValidate}>🛡️ Run validation frameworks</Button><OutputBox>{output.validate || <Placeholder>SWOT, Jobs-to-be-Done & a Founder-Fit score will be generated here.</Placeholder>}</OutputBox></>}
                            {view === "deck" && <><Field label="Startup one-liner" value={deckIdea} onChange={setDeckIdea} /><Button primary onClick={generateDeck}>🎞️ Build 12-slide deck</Button><OutputBox>{output.deck || <Placeholder>An investor-ready deck outline with slide-by-slide content will render here.</Placeholder>}</OutputBox></>}
                            {view === "research" && <><Field label="Market / industry to research" value={resTopic} onChange={setResTopic} /><Button primary onClick={generateResearch}>🔭 Run autonomous research</Button><OutputBox>{output.research || <Placeholder>Competitive landscape, market sizing, and trend synthesis will appear here.</Placeholder>}</OutputBox></>}
                            {view === "outreach" && <><div className="mb-4"><label className="mb-1.5 block text-[13px] font-medium text-[var(--muted)]">Outreach type</label><select value={outType} onChange={e => setOutType(e.target.value)} className="w-full rounded-[11px] border border-[var(--line-2)] bg-[var(--glass-04)] px-3.5 py-3 text-sm text-[var(--text)] outline-none focus:border-[var(--brand)]"><option>Investor cold email</option><option>LinkedIn connection note</option><option>Design-partner outreach</option></select></div><Field label="Recipient" value={outName} onChange={setOutName} /><Button primary onClick={generateOutreach}>✍️ Draft personalized message</Button><OutputBox>{output.outreach || <Placeholder>A personalized, ready-to-send draft will appear here.</Placeholder>}</OutputBox></>}
                        </div>}
                    </div>
                </div>
            </div></Reveal>
        </div></section>
    )
}